### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Overover1400** [oscarvgg/power-aso#2]
I tried this but it does not work for me :
$ power-aso scores -s g -k cat

TypeError: Cannot read property 'map' of undefined
    at C:\Users\hamed\AppData\Roaming\npm\node_modules\power-aso\node_modules\ramda\dist\ramda.js:578:31
    at Object.f2 [as map] (C:\Users\hamed\AppData\Roaming\npm\node_modules\power-aso\node_modules\ramda\dist\ramda.js:473:22)
    at Object.extract (C:\Users\hamed\AppData\Roaming\npm\node_modules\power-aso\node_modules\google-play-scraper\lib\utils\appList.js:44:12)
    at processAndRecur (C:\Users\hamed\AppData\Roaming\npm\node_modules\power-aso\node_modules\google-play-scraper\lib\search.js:19:24)
    at C:\Users\hamed\AppData\Roaming\npm\node_modules\power-aso\node_modules\google-play-scraper\lib\search.js:74:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by filippkowalski** [comment]
bump ^
